"""Baseline schema — creates all tables from the current ORM metadata.

This initial revision builds the full schema in one shot so existing
deployments can be stamped and future changes use autogenerated revisions.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-13
"""
from typing import Sequence, Union

from alembic import op

from app.core.database import Base
import app.models  # noqa: F401 — registers all tables on Base.metadata

revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
